services:
  - type: web
  - name: laravel-app
    env: php
    plan: free
    buildCommand: "composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache"
    startCommand: "apache2-foreground" # Atau sesuaikan dengan web server yang digunakan Render
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false